export const CONTEST_DATA_LOADING = 'CONTEST_DATA_LOADING';
export const CONTEST_DATA_SET = 'CONTEST_DATA_SET';
export const CONTEST_DATA_ERROR = 'CONTEST_DATAERROR';



export const USER_AUTH_LOADING = 'USER_AUTH_LOADING';
export const USER_AUTH_SET = 'USER_AUTH_SET';
export const USER_AUTH_ERROR = 'USER_AUTH_ERROR';
export const USER_RESET = 'USER_RESET';

export const TODO_LOADING = 'TODO_LOADING';
export const TODO_SET = 'TODO_SET';
export const TODO_ERROR = 'TODO_ERROR';